export { B1_BASIS_FOR_PREPARATION } from "./b1";
export { B2_PRACTICES_POLICIES } from "./b2";
export { B3_ENERGY_GHG } from "./b3";
export {
  B4_POLLUTION,
  B5_BIODIVERSITY,
  B6_WATER,
  B7_CIRCULAR_ECONOMY_WASTE,
} from "./b4-b7";
export {
  B8_WORKFORCE_GENERAL,
  B9_HEALTH_SAFETY,
  B10_REMUNERATION_TRAINING,
  B11_CONVICTIONS,
} from "./b8-b11";
export {
  C1_STRATEGY,
  C2_COMPREHENSIVE_PRACTICES,
  C3_GHG_TARGETS,
  C4_CLIMATE_RISKS,
  C5_WORKFORCE_ADDITIONAL,
  C6_HUMAN_RIGHTS,
  C7_HUMAN_RIGHTS_INCIDENTS,
  C8_REVENUES_BENCHMARKS,
  C9_GENDER_DIVERSITY,
} from "./c1-c9";
