import type { VsmeSchema } from "./vsme.types";
import {
  B1_BASIS_FOR_PREPARATION,
  B2_PRACTICES_POLICIES,
  B3_ENERGY_GHG,
  B4_POLLUTION,
  B5_BIODIVERSITY,
  B6_WATER,
  B7_CIRCULAR_ECONOMY_WASTE,
  B8_WORKFORCE_GENERAL,
  B9_HEALTH_SAFETY,
  B10_REMUNERATION_TRAINING,
  B11_CONVICTIONS,
  C1_STRATEGY,
  C2_COMPREHENSIVE_PRACTICES,
  C3_GHG_TARGETS,
  C4_CLIMATE_RISKS,
  C5_WORKFORCE_ADDITIONAL,
  C6_HUMAN_RIGHTS,
  C7_HUMAN_RIGHTS_INCIDENTS,
  C8_REVENUES_BENCHMARKS,
  C9_GENDER_DIVERSITY,
} from "./sections";

/**
 * Canonical VSME registry aligned with EFRAG VSME Standard (Dec 2024) and
 * Digital Template v1.1.0 (Oct 2025) named-range conventions.
 */
export const VSME_SCHEMA: VsmeSchema = {
  version: "2.0.0",
  standard: "VSME",
  alignment: "EFRAG",
  templateVersion: "1.1.0",
  sections: [
    B1_BASIS_FOR_PREPARATION,
    B2_PRACTICES_POLICIES,
    B3_ENERGY_GHG,
    B4_POLLUTION,
    B5_BIODIVERSITY,
    B6_WATER,
    B7_CIRCULAR_ECONOMY_WASTE,
    B8_WORKFORCE_GENERAL,
    B9_HEALTH_SAFETY,
    B10_REMUNERATION_TRAINING,
    B11_CONVICTIONS,
    C1_STRATEGY,
    C2_COMPREHENSIVE_PRACTICES,
    C3_GHG_TARGETS,
    C4_CLIMATE_RISKS,
    C5_WORKFORCE_ADDITIONAL,
    C6_HUMAN_RIGHTS,
    C7_HUMAN_RIGHTS_INCIDENTS,
    C8_REVENUES_BENCHMARKS,
    C9_GENDER_DIVERSITY,
  ],
};
